#!/usr/bin/env npx tsx
// ═══════════════════════════════════════════════════════════════════════════════
// Manifest — Contract Deployment Script
//
// Usage:
//   npm run deploy              → deploy to both preview + preprod
//   npm run deploy:preview      → deploy to preview only
//   npm run deploy:preprod      → deploy to preprod only
//
// NOTE: Real contract addresses are generated by the Midnight network
// during an actual deployment transaction. This script cannot create
// real addresses — it must use the Midnight SDK to deploy.
// ═══════════════════════════════════════════════════════════════════════════════

import { execSync } from 'child_process'
import { writeFileSync, existsSync, readFileSync } from 'fs'
import { resolve } from 'path'

const ROOT_DIR = resolve(import.meta.dirname, '..')
const MANAGED_DIR = resolve(ROOT_DIR, 'managed')
const ENV_FILE = resolve(ROOT_DIR, '.env.local')
const README_PATH = resolve(ROOT_DIR, 'README.md')

// Determine which networks to deploy to
const networks: string[] = (() => {
  if (process.argv.includes('--network')) {
    const idx = process.argv.indexOf('--network')
    return [process.argv[idx + 1]]
  }
  if (process.argv.includes('--preview')) return ['preview']
  if (process.argv.includes('--preprod')) return ['preprod']
  return ['preview', 'preprod']
})()

/**
 * Deploy to a single network using the Midnight SDK.
 * Returns the real contract address from the blockchain.
 *
 * In production, this calls:
 *   compact-cli deploy --contract managed/ --network <network>
 *
 * The Midnight SDK will:
 *   1. Create a deployment transaction
 *   2. Sign it with the deployer wallet
 *   3. Submit to the network
 *   4. Return the real contract address
 */
function deployToNetwork(network: string): string {
  const deploymentFile = resolve(ROOT_DIR, `.deployment.${network}.json`)

  console.log('═══════════════════════════════════════════════')
  console.log(` 🚀 DEPLOYING TO ${network.toUpperCase()}`)
  console.log('═══════════════════════════════════════════════\n')

  // Check for existing deployment
  const isUpgrade = existsSync(deploymentFile)
  if (isUpgrade) {
    const existing = JSON.parse(readFileSync(deploymentFile, 'utf-8'))
    console.log(`📦 Existing deployment found — UPGRADING`)
    console.log(`   Previous address: ${existing.contractAddress}\n`)
  }

  // Step 1: Check proof server
  console.log('🔍 Checking proof server...')
  try {
    const health = execSync('curl -s http://localhost:6300/health', { encoding: 'utf-8' })
    console.log(`   ✅ ${health.trim()}\n`)
  } catch {
    console.error('   ❌ Proof server not responding on port 6300')
    console.error('   Start it with: docker start manifest-proof-server')
    process.exit(1)
  }

  // Step 2: Check compilation artifacts
  console.log('📦 Checking compilation artifacts...')
  if (!existsSync(MANAGED_DIR)) {
    console.error('   ❌ managed/ not found. Run `npm run compile` first.')
    process.exit(1)
  }
  console.log('   ✅ Artifacts found\n')

  // Step 3: Deploy via Midnight SDK
  console.log('🔐 Deploying contract to Midnight network...')
  console.log('   This will:')
  console.log('   1. Create a deployment transaction')
  console.log('   2. Generate a ZK proof for the constructor')
  console.log('   3. Submit to the Midnight ledger')
  console.log('   4. Receive a REAL contract address from the network\n')

  // In production, this would be:
  //   const result = execSync(
  //     `npx compact-cli deploy --contract managed/ --network ${network}`,
  //     { cwd: ROOT_DIR, encoding: 'utf-8' }
  //   )
  //   const contractAddress = parseAddressFromOutput(result)

  // For now, we need the user to deploy manually and provide the address
  console.log('⚠️  MANUAL DEPLOYMENT REQUIRED')
  console.log('   To get a real contract address, run:')
  console.log('')
  console.log(`   npx compact-cli deploy --contract managed/ --network ${network}`)
  console.log('')
  console.log('   Or deploy via the Midnight CLI wallet:')
  console.log(`   https://docs.midnight.network/getting-started/hello-world`)
  console.log('')

  // Check if address was provided as argument
  const addrIdx = process.argv.indexOf('--address')
  let contractAddress: string

  if (addrIdx !== -1 && process.argv[addrIdx + 1]) {
    // Address provided via CLI
    contractAddress = process.argv[addrIdx + 1]
    console.log(`✅ Using provided address: ${contractAddress}\n`)
  } else if (isUpgrade) {
    // Reuse previous address for upgrades
    const existing = JSON.parse(readFileSync(deploymentFile, 'utf-8'))
    contractAddress = existing.contractAddress
    console.log(`✅ Reusing previous address: ${contractAddress}\n`)
  } else {
    console.log('   After deploying, re-run with:')
    console.log(`   npm run deploy:${network} -- --address <REAL_ADDRESS>`)
    console.log('')
    process.exit(1)
  }

  // Save deployment info
  writeFileSync(deploymentFile, JSON.stringify({
    network,
    contractAddress,
    deployedAt: new Date().toISOString(),
    isUpgrade,
  }, null, 2))
  console.log(`📝 Saved to .deployment.${network}.json\n`)

  // Update README
  if (existsSync(README_PATH)) {
    let readme = readFileSync(README_PATH, 'utf-8')
    const label = network.charAt(0).toUpperCase() + network.slice(1)
    const regex = new RegExp(`\\|\\s*${label}\\s*\\|\\s*\`[^\`]+\`\\s*\\|`, 'i')
    readme = readme.replace(regex, `| ${label}  | \`${contractAddress}\` |`)
    writeFileSync(README_PATH, readme)
    console.log('✅ Updated README.md\n')
  }

  return contractAddress
}

// ─── Main ──────────────────────────────────────────────────────────────────

function main() {
  console.log('═══════════════════════════════════════════════')
  console.log(' Manifest — Contract Deployment')
  console.log(` Networks: ${networks.join(', ')}`)
  console.log('═══════════════════════════════════════════════\n')

  const addresses: Record<string, string> = {}
  for (const network of networks) {
    addresses[network] = deployToNetwork(network)
  }

  // Write .env.local
  const defaultNetwork = networks.includes('preview') ? 'preview' : networks[0]
  const envContent = [
    '# Manifest — Deployment Configuration',
    `# Generated: ${new Date().toISOString()}`,
    '',
    `NEXT_PUBLIC_NETWORK=${defaultNetwork}`,
    `NEXT_PUBLIC_CONTRACT_ADDRESS=${addresses[defaultNetwork]}`,
    'NEXT_PUBLIC_PROOF_SERVER_URL=http://localhost:6300',
    '',
  ].join('\n')
  writeFileSync(ENV_FILE, envContent)
  console.log(`✅ Written to .env.local\n`)

  // Summary
  console.log('═══════════════════════════════════════════════')
  console.log(' ✅ DEPLOYMENT COMPLETE')
  console.log('═══════════════════════════════════════════════')
  for (const [net, addr] of Object.entries(addresses)) {
    console.log(` ${net}: ${addr}`)
  }
  console.log('═══════════════════════════════════════════════\n')
}

main()
